// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventryManagement.Core.Models.Entities;

public partial class Product
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public int? CategoryId { get; set; }

    public int? SupplierId { get; set; }

    public decimal Price { get; set; }

    public int? QuantityInStock { get; set; }

    public virtual Category Category { get; set; }

    public virtual Supplier Supplier { get; set; }
}