// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventryManagement.Core.Models.Entities;

public partial class Supplier
{
    public int SupplierId { get; set; }

    public string SupplierName { get; set; }

    public string ContactNumber { get; set; }

    public string Address { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}